In [1]:
import numpy
numpy.__version__

'1.16.4'

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])

In [3]:
print(a)
print(type(a))
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32


In [4]:
print(a[0])

1


In [5]:
a[3]=99
print(a)

[ 1  2  3 99  5]


 # MATRIX CREATION 

## No of sublists is the number of rows and the number of elements in one sublist is number of columns

In [6]:
a= np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [7]:
a=np.array([[1,2,3,4]])
print(a)
print(a.shape)

[[1 2 3 4]]
(1, 4)


In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


## Indexing of a Matrix

In [9]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a[0,3])
a[1,1]=99
print(a)

[[1 2 3 4]
 [5 6 7 8]]
4
[[ 1  2  3  4]
 [ 5 99  7  8]]


## creating a list first and then passing it to the array function

In [10]:
list1=[1,2,3,4]
list2=[[1,2,3],[4,5,6]]

a=np.array(list1)
print(a)
print(a.shape)

a=np.array(list2)
print(a)
print(a.shape)



[1 2 3 4]
(4,)
[[1 2 3]
 [4 5 6]]
(2, 3)


## Array Functions

In [11]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(a.reshape(2,5))
print(a.reshape(1,10)) # it will covert any dimesnion matrix into 2 dim matrix
print(a.reshape(-12,2)) # if you write a negative value then it will only care about the columns
print(a.reshape(1,-23)) #vica versa

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


## Ravel - It converts any dim matrix into 1 dim array(linearizes it to og 1D array form)

In [12]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
b=a.reshape(2,5)
print(b)
print(b.ravel())

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


## tolist - coverts 1d array into og list and 2d matrix into list of lists

In [13]:
list1=[1,2,3,4,5,6,7,8,9,10]
a=np.array(list1)
print(a)
print(type(a))

b=a.tolist()
print(b)
print(type(b))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [14]:
list1=[[1,2,3,4,5],[6,7,8,9,10]]
a=np.array(list1)
print(a)
print(type(a))

b=a.tolist()
print(b)
print(type(b))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
<class 'list'>


In [15]:
list1=(1,2,3,4,5,6,7,8,9,10)
a=np.array(list1)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [16]:
z=np.array([1,2])
print(z)
print(z.dtype)
z=np.array([1.2,2])
print(z)
print(z.dtype)
z=np.array([1,2],dtype=float)  #int into float or dtype=int for ulta
print(z)
print(z.dtype)

[1 2]
int32
[1.2 2. ]
float64
[1. 2.]
float64


In [17]:
## Frequently used arrays


In [18]:

a=np.zeros((2,3))
print(a)
print(a.dtype)

a=np.ones((2,3))
print(a)
print(a.dtype)


a=np.zeros((2,3),dtype=int)
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]]
float64
[[0 0 0]
 [0 0 0]]
int32


In [19]:
# MATRIX FULL OF 0 OR 1 OR ANY NUMBER

a=np.full((2,3),4)
print(a)
print(a.dtype)

a=np.full((2,3),4.)
print(a)
print(a.dtype)

a=np.full((2,3),0)
print(a)
print(a.dtype)

a=np.full((2,3),0,dtype=float)
print(a)
print(a.dtype)

[[4 4 4]
 [4 4 4]]
int32
[[4. 4. 4.]
 [4. 4. 4.]]
float64
[[0 0 0]
 [0 0 0]]
int32
[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [20]:
# IDENTITY MATRIX GENERATION
a=np.eye(3)
print(a)

a=np.eye(3,dtype=int)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
# RANDOM MATRIX GENERATION

In [22]:
a=np.random.random((3,3))
print(a)


a=np.random.randint(5,10,size=(3,3))
print(a)

[[0.08512441 0.90216509 0.785348  ]
 [0.57247943 0.56085767 0.37967356]
 [0.99289188 0.9411939  0.91825603]]
[[9 7 6]
 [6 7 7]
 [9 8 5]]


## Array slicing

In [23]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,4]]
a=np.array(a)
print(a)
print(a[0:2,1:3])

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
[[2 3]
 [5 6]]


In [24]:
print(a)
print(a[0:1,0:3])
print(a[:1,:-1])

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
[[1 2 3]]
[[1 2 3]]


In [25]:
print(a)
print(a[0:3:2,1:4:2])
print(a[::2,1::2])

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
[[2 4]
 [8 4]]
[[2 4]
 [8 4]]


In [26]:
#CHANGES IN THE SUBMATRIX WILL ALSO REFLECT IN PARENT MATRIX
a=[[1,2,3,4],[4,5,6,7],[7,8,9,4]]
a=np.array(a)
print(a)
b=a[0:3:2,1:4:2]
print(b)
b[0,0]=89999
print(b)
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
[[2 4]
 [8 4]]
[[89999     4]
 [    8     4]]
[[    1 89999     3     4]
 [    4     5     6     7]
 [    7     8     9     4]]


In [27]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,4]]
a=np.array(a)
print(a)
b=a[0:3:2,1:4:2]
c=b
print(b)
c[0,0]=89999
print(c)
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
[[2 4]
 [8 4]]
[[89999     4]
 [    8     4]]
[[    1 89999     3     4]
 [    4     5     6     7]
 [    7     8     9     4]]


In [31]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,4]]
a=np.array(a)
print(a)
print('*********************************************')
print(a[0:2,[0,1,3]])

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]
*********************************************
[[1 2 4]
 [4 5 7]]


In [32]:
# ELEMENTS GREATER THAN A SPECIFIC VALUE FROM A MATRIX

In [1]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,4]]
a=np.array(a)
print(a)
print('*********')
print(b=a>5)
print(a[b])

NameError: name 'np' is not defined

# ARRAY OPERATIONS
## ELEMENTWISE ARITHMETIC OPERATIONS:

In [37]:
a=[[1,2],[4,5]]
a=np.array(a)
print(a)
print('**************')
b=[[1,2],[4,5]]
b=np.array(b)
print(b)
print('***************')
print(a+b) #or print(np.add(a,b))
print('***************')
print(a-b) #or print(np.subtract(a,b))
print('***************')
print(a*b) #or print(np.multiply(a,b))
print('***************')
print(a/b) #or print(np.divide(a,b))
print('***************')

[[1 2]
 [4 5]]
**************
[[1 2]
 [4 5]]
***************
[[ 2  4]
 [ 8 10]]
***************
[[0 0]
 [0 0]]
***************
[[ 1  4]
 [16 25]]
***************
[[1. 1.]
 [1. 1.]]
***************


In [39]:
# SQURE ROOT 
print(a)
print(np.sqrt(a))

[[1 2]
 [4 5]]
[[1.         1.41421356]
 [2.         2.23606798]]


In [40]:
# DOT PRODUCT
a=[[1,2],[4,5]]
a=np.array(a)
b=[[2,3],[6,5]]
b=np.array(b)
v=np.array([1,2])
w=np.array([5,6])

print(v.dot(w)) #or
print(np.dot(v,w))

print(a.dot(v)) #or
print(np.dot(a,v))

print(a.dot(b)) #or
print(np.dot(a,b))

17
17
[ 5 14]
[ 5 14]
[[14 13]
 [38 37]]
[[14 13]
 [38 37]]


# SUM OF ELEMENTS

In [43]:
print(a)
print(np.sum(a))
print(np.sum(a,axis=0)) #y axix columns
print(np.sum(a,axis=1))#x axis rows

[[1 2]
 [4 5]]
12
[5 7]
[3 9]


# TRANSPOSE

In [46]:
print(a)
print(a.T)
b=[[1,2,3,4]]
b=np.array(b)
print(b.T)

[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
[[1]
 [2]
 [3]
 [4]]
